version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: threat_intel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/threat_intel
      - FRONTEND_URL=http://localhost:80
      - IPGEOLOCATION_API_KEY=0d5125f5ffec44f4bb9de281454a67e5
      - IP_API_KEY=0d5125f5ffec44f4bb9de281454a67e5
      - VIRUSTOTAL_API_KEY=23fd38ef1d87e445bba82cdfd469115d1642937f315b7f16d6a9be1a641080e5
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
